version: "3"

services:

  # frontend:
  #   build: ./frontend
  #   image: smars-frontend:latest
  #   ports:
  #     - "80:1234"
  #   depends_on:
  #     - backend
  #   networks:
  #     - smars_default

  backend:
    build: .
    image: smars-backend:latest
    ports:
      - "7000:7000"
      - "443:443"
    volumes:
      -  '/etc/letsencrypt/archive/freesmars.com:/usr/src/app/certificates'
    depends_on:
      - db
    networks:
      - smars_default

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - '/var/lib/docker/volumes/mongo:/data/db'
    networks:
      - smars_default
networks:
  smars_default:
