version: "3"

services:

  backend:
    build: .
    image: smars-backend:latest
    ports:
      - "7000:7000"
      - "443:443"
    volumes:
      -  '/etc/letsencrypt/archive/freesmars.com:/usr/src/app/certificates'
    depends_on:
      - db
    networks:
      - smars_default

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - '/var/lib/docker/volumes/mongo:/data/db'
    networks:
      - smars_default
networks:
  smars_default:
