version: "3"

services:

  backend:
    build:
      context: .
      args:
        - SMARS_ENVIRONMENT=${SMARS_ENVIRONMENT}
        - DOMAIN_NAME=${DOMAIN_NAME}
    image: danatack/smars:latest
    environment:
      - ENVIRONMENT=${SMARS_ENVIRONMENT}
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      -  "/etc/letsencrypt/archive/${DOMAIN_NAME}:/usr/src/app/certificates"
    depends_on:
      - db
    networks:
      - smars_default
    restart: unless-stopped

  db:
    image: mongo:6.0.9
    ports:
      - 27017:27017
    volumes:
      - '/var/lib/docker/volumes/mongo:/data/db'
    networks:
      - smars_default
    restart: unless-stopped

networks:
  smars_default:
