version: "3"

services:

  backend:
    build:
      context: .
      args:
        - TF_VAR_smars_environment=$smars_environment
        - TF_VAR_domain_name=$domain_name
    image: smars-backend:latest
    ports:
      - "7000:7000"
      - "443:443"
    volumes:
      -  "/etc/letsencrypt/archive/${domain_name}:/usr/src/app/certificates"
    depends_on:
      - db
    networks:
      - smars_default
    restart: on-failure

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - '/var/lib/docker/volumes/mongo:/data/db'
    networks:
      - smars_default
    restart: on-failure

networks:
  smars_default:
