name: Basic CI

on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: echo "starting npm ci"
      - run: pwd
      - run: npm ci
      - run: echo "starting tests"
      - run: npm run test
