name: Build Docker Image

# Only trigger a build when a merge/commit is made to the master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SMARS_ENVIRONMENT: 'production'
      DOMAIN_NAME: 'freesmars.com'
      DOCKER_REPO: 'danatack/smars'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u danatack -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: bash startBuild.sh

      - name: Log out from Docker Hub
        run: docker logout
